### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xingyezhuifeng** [albert100121/360SD-Net#3]
tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

Could you please help me?

**Comment by albert100121** [comment]
Hi @xingyezhuifeng 
Could you provide more detail?
Thank you.

**Comment by Ren-Lex** [comment]
I have this error too.

Traceback (most recent call last):
  File "main.py", line 360, in <module>
    main()
  File "main.py", line 295, in main
    for batch_idx, (imgU_crop, imgD_crop,
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/renyibin/360SD-Net/dataloader/RGB_Loader.py", line 64, in __getitem__
    up_img = processed(up_img)
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/renyibin/anaconda3/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
